### ISSUE TITLE
最新master版本使用poetry构建运行，测试arzon爬虫刮削失败

### ISSUE THREAD

**Issue by csh90917** [Yuukiy/JavSP#429]
### 问题详情

拉取最新master版本，windows运行环境，通过poetry构建运行

修改config.yml配置的crawler字段，normal只设置了arzon，如下：

```
crawler:
  # 要使用的爬虫列表（汇总数据时从前到后进行）
  # airav avsox avwiki fanza fc2 fc2fan javbus javdb javlib javmenu jav321 mgstage prestige arzon arzon_iv
  selection:
    #normal: [arzon, arzon_iv, airav, avsox, javbus, javdb, javlib, jav321, mgstage, prestige]
    normal: [arzon]
    fc2: [fc2, avsox, javdb, javmenu, fc2ppvdb]
    cid: [fanza]
    getchu: [dl_getchu]
    gyutto: [gyutto]
```

测试刮削单个影片（车牌 SL-179）

手动搜索能在arzon网页找到对应影片的详细信息，使用JavSP刮削提示刮削失败

使用代理跟不使用代理的情况均尝试过，结果一样

源代码运行无法找到系统输出日志，尝试在web/arzon模块添加print函数也无法在控制台输出

执行截图：

![arzon爬虫失效截图](https://github.com/user-attachments/assets/7efd6909-1564-409f-9bff-3a2d4495efb7)

希望解答下

1. 是不是我哪里操作失误了
2. 同时希望了解目前源代码运行的错误日志或者info会输出到哪里
3. 以及如何添加打印信息才能在本地调试爬虫脚本时显示在控制台
4. 本地是否可以通过源代码打包出windows可执行版本使用可视化控件的功能

### 运行方式

我是从源代码运行的

### 代理

否

### 日志

源代码运行无法找到日志文件

### 运行截图（可选）

![arzon爬虫失效截图](https://github.com/user-attachments/assets/618db78c-966d-4276-b553-5f42e8a35839)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。
